<?php
/**
 * Article review template
 */

if (!defined('ABSPATH')) {
    exit;
}
?>

<div class="wrap">
    <h1><?php _e('Article Review', 'medical-news-automation'); ?></h1>
    
    <?php if (!empty($articles)): ?>
        <div class="mna-articles-review">
            <?php foreach ($articles as $article): ?>
                <div class="mna-review-item" data-article-id="<?php echo $article->id; ?>">
                    <div class="review-header">
                        <h2><?php echo esc_html($article->headline); ?></h2>
                        <div class="article-meta">
                            <span class="generated-by"><?php echo __('Generated by:', 'medical-news-automation') . ' ' . strtoupper($article->llm_used); ?></span>
                            <span class="quality-score"><?php echo __('Quality Score:', 'medical-news-automation') . ' ' . ($article->content_quality_score ?: 'N/A') . '/10'; ?></span>
                            <span class="created-date"><?php echo human_time_diff(strtotime($article->created_at)) . ' ' . __('ago', 'medical-news-automation'); ?></span>
                        </div>
                    </div>
                    
                    <div class="review-content">
                        <div class="sources-section">
                            <h3><?php _e('Research Sources', 'medical-news-automation'); ?></h3>
                            <?php 
                            $sources = json_decode($article->sources_json, true);
                            if (!empty($sources)): 
                            ?>
                                <ul class="sources-list">
                                    <?php foreach ($sources as $source): ?>
                                        <li>
                                            <a href="<?php echo esc_url($source['url']); ?>" target="_blank" rel="noopener">
                                                <?php echo esc_html($source['title'] ?: $source['domain'] ?: $source['url']); ?>
                                            </a>
                                            <?php if (!empty($source['credibility_score'])): ?>
                                                <span class="credibility-score">(Credibility: <?php echo $source['credibility_score']; ?>/10)</span>
                                            <?php endif; ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php else: ?>
                                <p><?php _e('No sources available.', 'medical-news-automation'); ?></p>
                            <?php endif; ?>
                        </div>
                        
                        <div class="article-content">
                            <h3><?php _e('Generated Article', 'medical-news-automation'); ?></h3>
                            <div class="article-text">
                                <?php echo wpautop(esc_html($article->generated_content)); ?>
                            </div>
                        </div>
                    </div>
                    
                    <div class="review-actions">
                        <div class="review-notes">
                            <label for="review-notes-<?php echo $article->id; ?>">
                                <?php _e('Review Notes:', 'medical-news-automation'); ?>
                            </label>
                            <textarea id="review-notes-<?php echo $article->id; ?>" 
                                      class="review-notes-field large-text" rows="3"
                                      placeholder="<?php _e('Add your review notes here...', 'medical-news-automation'); ?>"></textarea>
                        </div>
                        
                        <div class="action-buttons">
                            <button class="button button-primary approve-article" 
                                    data-article-id="<?php echo $article->id; ?>" 
                                    data-action="approve">
                                <?php _e('Approve', 'medical-news-automation'); ?>
                            </button>
                            
                            <button class="button button-secondary publish-article" 
                                    data-article-id="<?php echo $article->id; ?>" 
                                    data-action="publish">
                                <?php _e('Approve & Publish', 'medical-news-automation'); ?>
                            </button>
                            
                            <button class="button request-changes" 
                                    data-article-id="<?php echo $article->id; ?>" 
                                    data-action="request_changes">
                                <?php _e('Request Changes', 'medical-news-automation'); ?>
                            </button>
                            
                            <button class="button reject-article" 
                                    data-article-id="<?php echo $article->id; ?>" 
                                    data-action="reject" 
                                    style="color: #d63638;">
                                <?php _e('Reject', 'medical-news-automation'); ?>
                            </button>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <div class="mna-empty-state">
            <h2><?php _e('No Articles for Review', 'medical-news-automation'); ?></h2>
            <p><?php _e('There are currently no articles awaiting review.', 'medical-news-automation'); ?></p>
            <a href="<?php echo admin_url('admin.php?page=mna-headlines'); ?>" class="button button-primary">
                <?php _e('Add Headlines to Process', 'medical-news-automation'); ?>
            </a>
        </div>
    <?php endif; ?>
</div>

<style>
.mna-review-item {
    background: #fff;
    margin-bottom: 30px;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    overflow: hidden;
}

.review-header {
    padding: 20px;
    border-bottom: 1px solid #eee;
    background: #f9f9f9;
}

.review-header h2 {
    margin: 0 0 10px 0;
    color: #333;
}

.article-meta {
    display: flex;
    gap: 20px;
    font-size: 13px;
    color: #666;
}

.review-content {
    display: grid;
    grid-template-columns: 1fr 2fr;
    gap: 0;
}

.sources-section {
    padding: 20px;
    border-right: 1px solid #eee;
    background: #fafafa;
}

.sources-section h3 {
    margin-top: 0;
    font-size: 16px;
}

.sources-list {
    list-style: none;
    padding: 0;
}

.sources-list li {
    margin-bottom: 10px;
    padding: 8px;
    background: #fff;
    border-radius: 4px;
    border-left: 3px solid #3498db;
}

.sources-list a {
    text-decoration: none;
    font-weight: 500;
}

.credibility-score {
    font-size: 11px;
    color: #666;
    margin-left: 10px;
}

.article-content {
    padding: 20px;
}

.article-content h3 {
    margin-top: 0;
    font-size: 16px;
}

.article-text {
    line-height: 1.6;
    color: #333;
    font-size: 14px;
}

.review-actions {
    padding: 20px;
    border-top: 1px solid #eee;
    background: #f9f9f9;
}

.review-notes {
    margin-bottom: 15px;
}

.review-notes label {
    display: block;
    margin-bottom: 5px;
    font-weight: 600;
}

.action-buttons {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
}

.mna-empty-state {
    text-align: center;
    padding: 60px 20px;
    background: #fff;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.button.loading {
    opacity: 0.6;
    pointer-events: none;
}

@media (max-width: 768px) {
    .review-content {
        grid-template-columns: 1fr;
    }
    
    .sources-section {
        border-right: none;
        border-bottom: 1px solid #eee;
    }
    
    .action-buttons {
        flex-direction: column;
    }
}
</style>

<script>
jQuery(document).ready(function($) {
    // Handle review actions
    $('.approve-article, .publish-article, .request-changes, .reject-article').on('click', function() {
        var button = $(this);
        var articleId = button.data('article-id');
        var action = button.data('action');
        var notes = $('#review-notes-' + articleId).val();
        
        // Confirmation for reject action
        if (action === 'reject' && !confirm('<?php _e('Are you sure you want to reject this article?', 'medical-news-automation'); ?>')) {
            return;
        }
        
        // Disable all buttons for this article
        var articleContainer = button.closest('.mna-review-item');
        articleContainer.find('.action-buttons button').addClass('loading').prop('disabled', true);
        
        $.post(ajaxurl, {
            action: 'mna_approve_article',
            article_id: articleId,
            action_type: action,
            notes: notes,
            nonce: mna_ajax.nonce
        }, function(response) {
            if (response.success) {
                // Show success message
                var message = response.data.message;
                
                // Remove the article from view or update its status
                if (action === 'publish' || action === 'approve' || action === 'reject') {
                    articleContainer.fadeOut(500, function() {
                        $(this).remove();
                        
                        // Check if there are any articles left
                        if ($('.mna-review-item').length === 0) {
                            location.reload();
                        }
                    });
                } else {
                    // Re-enable buttons for request changes
                    articleContainer.find('.action-buttons button').removeClass('loading').prop('disabled', false);
                }
                
                // Show notification
                $('<div class="notice notice-success is-dismissible"><p>' + message + '</p></div>')
                    .insertAfter('.wrap h1');
                
            } else {
                // Re-enable buttons on error
                articleContainer.find('.action-buttons button').removeClass('loading').prop('disabled', false);
                alert('Error: ' + response.data.message);
            }
        }).fail(function() {
            // Re-enable buttons on failure
            articleContainer.find('.action-buttons button').removeClass('loading').prop('disabled', false);
            alert('<?php _e('Request failed. Please try again.', 'medical-news-automation'); ?>');
        });
    });
});
</script>